# Default values for voice-changer Helm chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global settings
global:
  appName: voice-changer

# API Server configuration
api:
  name: api
  replicaCount: 1

  image:
    repository: voice-changer-api
    tag: latest
    pullPolicy: Never  # Set to Never for local minikube images

  service:
    type: NodePort
    port: 8000
    targetPort: 8000
    nodePort: 30900

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"

  livenessProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 10
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 5

  nodeAffinity: {}

# Worker configuration
worker:
  name: worker
  replicaCount: 3

  image:
    repository: voice-changer-worker
    tag: latest
    pullPolicy: Never  # Set to Never for local minikube images

  service:
    type: NodePort
    port: 8001
    targetPort: 8001
    nodePort: 30901

  # Environment variables for worker pods
  env:
    pythonUnbuffered: "1"
    apiUrl: "http://voice-changer-api:8000"

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  livenessProbe:
    httpGet:
      path: /health
      port: 8001
    initialDelaySeconds: 10
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /health
      port: 8001
    initialDelaySeconds: 5
    periodSeconds: 5

  nodeAffinity: {}

# Frontend configuration
frontend:
  name: frontend
  replicaCount: 1

  image:
    repository: voice-changer-frontend
    tag: latest
    pullPolicy: Never  # Set to Never for local minikube images

  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30000

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"

  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 5

  nodeAffinity: {}

# TURN server configuration
turn:
  enabled: false
  name: turn
  replicaCount: 1

  image:
    repository: coturn/coturn
    tag: "4.6.2"
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    annotations: {}
    loadBalancerIP: ""
    externalTrafficPolicy: ""

  hostNetwork: false

  ports:
    tcp: 3478
    tls: 5349
    udp:
      min: 49152
      max: 49252

  relay:
    realm: voice-changer.example.com
    publicIP: ""

  credentials:
    static:
      enabled: true
      username: voice-user
      password: change-me
      existingSecret: ""

  resources: {}
  nodeAffinity: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
