# Default values for voice-changer Helm chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global settings
global:
  appName: voice-changer

# API Server configuration
api:
  name: api
  replicaCount: 3

  image:
    repository: voice-changer-api
    tag: latest
    pullPolicy: Never  # Set to Never for local minikube images

  service:
    type: NodePort
    port: 9000
    targetPort: 9000
    nodePort: 9000

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"

  livenessProbe:
    httpGet:
      path: /health
      port: 9000
    initialDelaySeconds: 10
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /health
      port: 9000
    initialDelaySeconds: 5
    periodSeconds: 5

  nodeAffinity: {}

# Worker configuration
worker:
  name: worker
  replicaCount: 1

  image:
    repository: voice-changer-worker
    tag: latest
    pullPolicy: Never  # Set to Never for local minikube images

  service:
    type: NodePort
    port: 9001
    targetPort: 9001
    nodePort: 9001

  # Environment variables for worker pods
  env:
    pythonUnbuffered: "1"
    apiUrl: "http://voice-changer-api:9000"

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  livenessProbe:
    httpGet:
      path: /health
      port: 9001
    initialDelaySeconds: 10
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /health
      port: 9001
    initialDelaySeconds: 5
    periodSeconds: 5

  nodeAffinity: {}

# Frontend configuration
frontend:
  name: frontend
  replicaCount: 1

  image:
    repository: voice-changer-frontend
    tag: latest
    pullPolicy: Never  # Set to Never for local minikube images

  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 3000

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"

  livenessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 5

  nodeAffinity: {}
