apiVersion: v1
kind: Service
metadata:
  name: voice-changer-api
  labels:
    app: voice-changer
    component: api
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30900
    protocol: TCP
    name: http
  selector:
    app: voice-changer
    component: api
