apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-changer-frontend
  labels:
    app: voice-changer
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice-changer
      component: frontend
  template:
    metadata:
      labels:
        app: voice-changer
        component: frontend
    spec:
      containers:
      - name: frontend
        image: voice-changer-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
