apiVersion: v1
kind: Service
metadata:
  name: voice-changer-frontend
  labels:
    app: voice-changer
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
    name: http
  selector:
    app: voice-changer
    component: frontend
