# kind-public-private.yaml
#
# Creates a kind cluster where the control-plane node exposes HTTP/HTTPS ports
# to the host machine while worker nodes remain private on the Docker network.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # Control plane acts as the public entry point for the API and TURN services.
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        protocol: TCP
  # Worker nodes are private with no host port mappings.
  - role: worker
  - role: worker
